flags:
  idris:
    gmp: true
    ffi: true
packages:
- location: '.'
- location: /home/j/dev/apps/plan9/custom/Idris-dev
  extra-dep: true
extra-deps:
- code-page-0.1.2
- idris-0.99.2
- libffi-0.1
- trifecta-1.6
resolver: lts-7.15
